### ISSUE TITLE
Clean code: "print" functions should only return data

### ISSUE THREAD

**Issue by samber** [samber/git-contrib-graph#18]
Only 1 function should be responsible for outputing results, depending of `--img`, `--json` or nothing.

Do not call `printf` or `println` from `print*********()` functions.

**Comment by korrat** [comment]
I would like to pick this up. 

Just to be clear, you want those functions to return a struct or an array that contains the information neatly formatted?

**Comment by samber** [comment]
yes !

Today, we print author contributions into loop iterations. We would like to return aggregated data and being able to call a "formatter" function printing output, depending of command parameters ;)
