### ISSUE TITLE
Add --json argument for json output

### ISSUE THREAD

**Issue by samber** [samber/git-contrib-graph#2]
Output contrib graph as JSON when --json is provided to the command. 🚀

**Comment by edenriquez** [comment]
can i take this ? @samber

**Comment by edenriquez** [comment]
sorry i went ahead 😬 hope it doesn't bother you

**Comment by samber** [comment]
@eduenriquez no problem 👌

**Comment by ananichev** [comment]
I'll take this one :)

**Comment by samber** [comment]
@ananichev Eduardo is on it already.

PR is pending for small changes.

But if you're looking for simple issues to start, you can take a look here: https://github.com/samber/git-contrib-graph/issues 😄
